spring:
  application:
    name: todo-think-server-java
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 3000

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null

logging:
  level:
    com.todothink: info
